### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by kctess5** [thinks/fast-marching-method#2]
Please consider adding a license to make it clear how your work can be used by others. I would like to be explore making an open source derivative work, so an open source license like the MIT license would be much appreciated.

Cheers!

**Comment by thinks** [comment]
Hi, 
Glad to hear that you would like to use my implementation of the fast marching method. I will try to find time to add a license. My intent is to make it as free as possible, so if you want to use it in the mean-time that is fine. I also realize that the documentation needs to improve. I hope to address this during the week.

**Comment by kctess5** [comment]
Sounds great, thank you!
