### ISSUE TITLE
vi 

### ISSUE THREAD

**Issue by MakeBestForYou** [thinks/fast-marching-method#4]
When I use make command,it show that I should add -std=gnu++11 or -std=c++11, so I add "add_compile_options(-std=c++11)" in the test/CMakeLists.txt, But it says  "error: parameter declared ‘auto’", My compiler is GNU 4.8.5. How do I solve this issue?

**Comment by thinks** [comment]
Is it possible that your compiler doesn't support C++17?

**Comment by MakeBestForYou** [comment]
Yea, I update the gcc version to 7.2, but get another error:  ’no name with ‘EikonalSolverBase’, this issue   like the issues another. And I use -fpermissive, but still build failed

**Comment by ccurtis0** [comment]
> another error: ’no name with ‘EikonalSolverBase’, [...]

@MakeBestForYou : If you can, try with the latest version. I think this is fixed.
